### ISSUE TITLE
How can i even possible remove images from datasets?

### ISSUE THREAD

**Issue by ElinLiu0** [roboflow/roboflow-python#142]
Hey,i wanna remove some unmarked images from my current datasets,how can i do?There's no button or options avaliable here.
![image](https://user-images.githubusercontent.com/75596885/234576910-7c7cfdef-522d-4fd0-8515-e3499ce3c143.png)

**Comment by xmsi** [comment]
double click to your image which you want delete. There is an option 
![Screenshot from 2023-08-24 16-19-00](https://github.com/roboflow/roboflow-python/assets/59314275/c31d5ac7-11b7-42b0-8ac7-01d05852419f)

**Comment by capjamesg** [comment]
@xmsi Thank you for your response to this issue -- greatly appreciated!

You can also drag over images in the user interface, then click the "Images Selected" button in the top right corner to delete multiple images:

<img width="1131" alt="Screenshot 2023-09-01 at 12 26 07" src="https://github.com/roboflow/roboflow-python/assets/37276661/5c33a37b-b50b-45f5-b904-e36d1ddace2b">

I am going to close this issue since it isn't part of `roboflow-python`. If you have further questions about the web application, please leave them on the [Roboflow Forum](https://discuss.roboflow.com).
