### ISSUE TITLE
Roboflow training failed

### ISSUE THREAD

**Issue by drakshayanidesai** [roboflow/roboflow-python#160]
I am using synthetic images  and yolo annotations generated from blender using python script. Then created my_darknet.label file and uploaded on roboflow. There are around 1000 images for training. The training failed showing the error(attached)
![MicrosoftTeams-image (1)](https://github.com/roboflow/roboflow-python/assets/94036159/e6bd37b1-37c9-4f4d-b5d8-e6cd9c09aba2)
Waiting for your suggestion

**Comment by capjamesg** [comment]
@drakshayanidesai Thank you for leaving this issue! If this is still a problem, could you send an email to support@roboflow.com from the email associated with your Roboflow account?

I am going to close this issue since it pertains to the Roboflow web platform rather than the `roboflow-python` package. We can continue the discussion over email so we can investigate the specifics of your project and provide more support.
